version: 2
updates:
  # Enable version updates for Java
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(maven): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 50
