status = [
  "continuous-integration/jenkins/branch",
  "Smoke tests on macos-latest",
  "Smoke tests on windows-2022",
  "Smoke tests on ubuntu-latest"
]

required_approvals = 1

delete_merged_branches = true

commit_title = "merge: ${PR_REFS}"

# Also cuts the marker, not just after
cut_body_after = "<!-- Cut-off marker"
