name: Space delimit branches
on:
  workflow_dispatch: {}
jobs:
  branches:
    name: Space delimited branches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: branches
        shell: bash
        run: |
          branches=$(git branch --list --all | grep 'origin/stable/' | cut -c 18- )
          space_delimited=${branches//$'\n'/ }
          echo "BRANCHES=${space_delimited}" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.branches.outputs.BRANCHES }}"