name: Integration tests

on:
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ["n1-standard-32-netssd-preempt"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.5
      - run: mvn -T1C -B -DskipChecks -DskipTests package
      - run: docker build --build-arg DISTBALL=dist/target/camunda-zeebe-*.tar.gz --build-arg APP_ENV=dev -t camunda/zeebe:current-test .
      - run: mvn -T1C -B -D skipUTs -D skipChecks verify
      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Integration Tests
          fail_if_no_tests: false
