name: Integration tests

on:
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ["n1-standard-32-netssd-preempt"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: mvn -T1C -B -D skipUTs -D skipChecks verify
      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Integration Tests
          fail_if_no_tests: false
