name: Tests

on:
  pull_request:

jobs:
  integration-tests:
    runs-on: ["n1-standard-32-netssd-preempt"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.5
      - run: mvn -T1C -B -DskipChecks -DskipTests package
      - run: docker build --build-arg DISTBALL=dist/target/camunda-zeebe-*.tar.gz --build-arg APP_ENV=dev -t camunda/zeebe:current-test .
      - run: mvn -T2 -B -D skipUTs -D skipChecks -D junitThreadCount=8 -P parallel-tests verify
      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Integration Tests
          fail_if_no_tests: false
  unit-tests:
    runs-on: [ "n1-standard-32-netssd-preempt" ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.5
      - run: mvn -B -D skipITs -D skipChecks -D junitThreadCount=8 -P parallel-tests verify
      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Unit Tests
          fail_if_no_tests: false
  smoke-tests:
    # This name is hard-referenced from bors.toml
    # Remember to update that if this name, or the matrix.os changes
    name: Run smoke tests on ${{ matrix.os }}
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-2022, ubuntu-latest ]
    env:
      JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build relevant modules
        run: mvn -B -am -pl qa/integration-tests install -DskipTests -DskipChecks "-Dmaven.javadoc.skip=true" -T1C
      - name: Run smoke test
        run: mvn -B -pl qa/integration-tests verify -P smoke-test -DskipUTs -DskipChecks

