name: Unit tests

on:
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ["n1-standard-32-netssd-preempt"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.5
      - run: mvn -B -D skipITs -D skipChecks verify
      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
         check_name: Unit Tests
         fail_if_no_tests: false
