name: Unit tests

on:
  pull_request:
    branches: [ main ]

jobs:
  project-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get -y install jq
      - name: Get Project List
        id: list-projects
        run: echo "::set-output name=projects::$(find -wholename "./*/pom.xml" -exec dirname {} \; | jq --compact-output --raw-input [inputs])"
    outputs:
      matrix: ${{ steps.list-projects.outputs.projects }}
  unit-tests:
    needs: project-list
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.project-list.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: mvn -T1C -B -D skipTests -D skipChecks install
      - run: mvn -B -D skipITs -D skipChecks verify -pl ${{ matrix.project }}
      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Unit tests for ${{ matrix.project }}
          fail_if_no_tests: false
